<?php
print(PHP_EOL);
print(PHP_EOL);
print(PHP_EOL);
print(PHP_EOL);
print(PHP_EOL);
print(PHP_EOL);
print(PHP_EOL);
print(PHP_EOL);
print(PHP_EOL);
print(PHP_EOL);
print(PHP_EOL);
print(PHP_EOL);
print(PHP_EOL);
print(PHP_EOL);
print(PHP_EOL);
print(PHP_EOL);
print(PHP_EOL);
print(PHP_EOL);
print(PHP_EOL);
print(PHP_EOL);
print(PHP_EOL);
print(PHP_EOL);
print(PHP_EOL);
print(PHP_EOL);
print(PHP_EOL);
print(PHP_EOL);
print(PHP_EOL);
print(PHP_EOL);
print(PHP_EOL);
print(PHP_EOL);
print(PHP_EOL);
print(PHP_EOL);
print(PHP_EOL);
print(PHP_EOL);
print(PHP_EOL);
print(PHP_EOL);
print(PHP_EOL);
print(PHP_EOL);
print(PHP_EOL);
print(PHP_EOL);
print(PHP_EOL);
print(PHP_EOL);
print(PHP_EOL);
print(PHP_EOL);
print(PHP_EOL);
print(PHP_EOL);
print(PHP_EOL);
print(PHP_EOL);
print(PHP_EOL);
print(PHP_EOL);
print(PHP_EOL);
print(PHP_EOL);


$a = "Hoi gebruiker";
print $a;

$line = readline("");
print_r($a . " zegt " . $line);
?>